[build]
  command = "npm run build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Simple PDF handling - Netlify should serve files from root
[[redirects]]
  from = "/*.pdf"
  to = "/:splat.pdf"
  status = 200
  force = false
  headers = {Content-Type = "application/pdf"}

# Handle all other routes for SPA behavior - this should be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add headers for PDF files
[[headers]]
  for = "/*.pdf"
  [headers.values]
    Content-Type = "application/pdf"
    Cache-Control = "public, max-age=31536000"
    Access-Control-Allow-Origin = "*"

# Add headers for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
